name: Push to Deploy

on:
  push:
    branches:
      - master # Ou main, dependendo da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para a Action escrever no repositório

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Este passo pega o conteúdo da 'dist/', comita e empurra para a branch 'deploy'
      # mantendo o histórico da branch.
      - name: Deploy to deploy branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: deploy
          keep_files: false # Garante que arquivos deletados no build sejam removidos da branch